# Generated by Django 4.2.20 on 2025-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('official_name', models.CharField(max_length=100, unique=True)),
                ('cca2', models.CharField(max_length=10, unique=True)),
                ('languages', models.JSONField(default=list)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('timezones', models.JSONField(default=list)),
                ('currencies', models.JSONField(default=list)),
                ('flags', models.JSONField(default=dict)),
                ('coat_of_arms', models.JSONField(default=dict)),
                ('flag', models.CharField(max_length=2)),
            ],
        ),
    ]
