# Generated by Django 4.2.20 on 2025-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='coat_of_arms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='country',
            name='currencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='country',
            name='flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='country',
            name='official_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
